### ISSUE TITLE
update readme.md with instructions for hooking up private repos

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/git-azure#51]
@woloski, @johnnyhalife, would you mind taking a stab at adding a section about private repos to readme.md since you did the feature?

**Comment by johnnyhalife** [comment]
@tjanczuk I did but as I have other commits (like set_env_vars) I'll give you the markdown in here , is it ok?

``` markdown
## Using private repositories or other hosted-git providers
On the 0.5.0 we've added support for using not only Github open source repos, but its private repositories
and any http-based git repositories too. If you want to take advantage of this feature you need to use the remote url for your repository as follows 

`git clone https://{username}:{password}@github.com/my_very_private_org/my_secret_repo`

Basically this will tell the engine that you're cloning a repository that is private, and
which are the credentials you need to access it. Also the same applies to the **Submodule Applications sample**, as follows

`git azure app --setup dante.com --gitUrl https://{user}:{password}@github.com/my_private_dante`

The same approach applies to BitBucket or any other Hosted GIT that supports https/http.

**DISCLAIMER:** Private repositories work **because GitHub supports basic authentication 
over HTTPS for cloning repositories**. We cannot guarantee that the same approach will work
for your own server or any other provider.

```

**Comment by johnnyhalife** [comment]
## Using private repositories or other hosted-git providers

On the 0.5.0 we've added support for using not only Github open source repos, but its private repositories
and any http-based git repositories too. If you want to take advantage of this feature you need to use the remote url for your repository as follows 

`git clone https://{username}:{password}@github.com/my_very_private_org/my_secret_repo`

Basically this will tell the engine that you're cloning a repository that is private, and
which are the credentials you need to access it. Also the same applies to the **Submodule Applications sample**, as follows

`git azure app --setup dante.com --gitUrl https://{user}:{password}@github.com/my_private_dante`

The same approach applies to BitBucket or any other Hosted GIT that supports https/http.

**DISCLAIMER:** Private repositories work **because GitHub supports basic authentication 
over HTTPS for cloning repositories**. We cannot guarantee that the same approach will work
for your own server or any other provider.

**Comment by tjanczuk** [comment]
Thanks! I updated the readme.
